import { Footer } from '@/containers/Footer';
import { Navigation } from '@/containers/Navigation';
import { WhatsAppFloat } from '@/containers/WhatsAppFloat';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Santos Telecom',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <meta name="theme-color" content="var(--green)" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <Navigation />

        {children}

        <WhatsAppFloat />

        <Footer />
      </body>
    </html>
  );
}
